### ISSUE TITLE
Crane on Mac

### ISSUE THREAD

**Issue by qxhy123** [Dataman-Cloud/crane#444]
RT, crane能在docker for mac上运行吗?

**Comment by qxhy123** [comment]
在docker for mac最新版上执行option 1, 报错, 信息如下:
********************************************************
ERROR: command **dockerd** is NOT FOUND! Please make sure docker-engine>=1.12 is installed!
********************************************************

**Comment by vitan** [comment]
The ERROR is caused by the docker version check script: https://github.com/Dataman-Cloud/crane/blob/master/release/template/node-init.sh#L45 .

I am going to make a PR to fix it, or you have to try the option-2 for a workaround.

BTW: Issue in English is better, friendly to the Non-Chinese developers.

**Comment by upccup** [comment]
@qxhy123 we are working on it.  Before this you can try with option 2. Sorry for this.

**Comment by vitan** [comment]
We re-evaluated this issue, and do not think it is a good time to support MacOS, given that crane is a multi-nodes cluster manage tool, instead single-node.

This [Docker for Mac](https://docs.docker.com/docker-for-mac/) is a solution based on one-single vm , and we can predict that Crane-on-Mac is just a dev toy. I don't think there are people running MacOS-based production.

If you'd like to taste Crane on Mac, The alternative solution is: VirtualBox + CentOS/Ubuntu

**Comment by xiaods** [comment]
support mac env to devleopment, have a try!
