### ISSUE TITLE
MacOSX Docker Compose

### ISSUE THREAD

**Issue by roscopecoltran** [Dataman-Cloud/crane#622]
### Expected behavior
get docker compose build up all services 

### Actual behavior
not starting all services

 docker-compose up -d
```
WARNING: Image for service crane_registry was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Building crane
ERROR: Error parsing reference: "crane:" is not a valid repository/tag
```

I guess something is wrong with the tag variable of docker images.

### Information about the Issue
problems with the front-end if using docker-compose up -d with mac osx sierra

can you provide more details about Mac OSX boostrapping for Mac OSX/docker-machine (ip, volumes,...) ?

### Steps to reproduce the behavior

  1. cd deploy
  2.  docker-compose up -d

**Comment by xiaods** [comment]
sorry, it came across docker tag issue, let me fix it asap.

**Comment by xiaods** [comment]
```shell
$ docker-compose build
WARNING: The REGISTRY_PREFIX variable is not set. Defaulting to a blank string.
WARNING: The TAG variable is not set. Defaulting to a blank string.
```
you need setting the env first.

if you want to evaluate the project, you can use alternative way:

 CRANE_IP=<your eth0 ip> ./bin/build-push-or-up.sh up

don't use localhost, because the crane instance is wrap into a container, it can't access outside docker expose http port 2375, we should be use real ip to connect.
